# Generated by Django 6.0.1 on 2026-01-27 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilDonneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids (kg)')),
                ('groupe_sanguin', models.CharField(choices=[('INCONNU', 'Inconnu'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='INCONNU', max_length=10, verbose_name='Groupe sanguin')),
                ('groupe_sanguin_verrouille', models.BooleanField(default=False, verbose_name='Groupe sanguin verrouillé')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donneur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
