# Generated by Django 6.0.1 on 2026-01-27 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donneurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profildonneur',
            name='date_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profildonneur',
            name='groupe_sanguin',
            field=models.CharField(choices=[('INCONNU', 'Inconnu'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='INCONNU', max_length=7),
        ),
        migrations.AlterField(
            model_name='profildonneur',
            name='groupe_sanguin_verrouille',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profildonneur',
            name='poids',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profildonneur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_donneur', to=settings.AUTH_USER_MODEL),
        ),
    ]
