# Generated by Django 6.0.1 on 2026-01-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donneurs', '0002_alter_profildonneur_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profildonneur',
            name='nb_modifications_groupe',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
