# Generated by Django 6.0.1 on 2026-01-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donneurs', '0003_profildonneur_nb_modifications_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profildonneur',
            name='date_dernier_don',
            field=models.DateField(blank=True, null=True, verbose_name='Date du dernier don'),
        ),
    ]
