# Generated by Django 6.0.1 on 2026-01-29 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donneurs', '0004_profildonneur_date_dernier_don'),
        ('hopitaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateField(default=django.utils.timezone.now)),
                ('volume_ml', models.PositiveIntegerField(default=450)),
                ('valide', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='donneurs.profildonneur')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='hopitaux.hopital')),
            ],
        ),
    ]
