# Generated by Django 6.0.1 on 2026-01-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='groupe_sanguin',
            field=models.CharField(choices=[('INCONNU', 'Inconnu'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='INCONNU', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='don',
            name='volume_ml',
            field=models.PositiveIntegerField(default=450, help_text='Volume prélevé en ml'),
        ),
    ]
