# Generated by Django 6.0.1 on 2026-01-30 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hopitaux', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('INCONNU', 'Inconnu'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=7)),
                ('volume_ml', models.PositiveIntegerField()),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SATISFAITE', 'Satisfaite'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=15)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='hopitaux.hopital')),
            ],
        ),
    ]
