# Generated by Django 6.0.1 on 2026-01-30 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
        ('hopitaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandesang',
            name='contact',
            field=models.CharField(default=' 57 52 52 52 ', help_text='Téléphone ou WhatsApp du demandeur', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandesang',
            name='hopital_autre',
            field=models.CharField(blank=True, help_text='À renseigner si l’hôpital n’est pas dans la liste', max_length=255),
        ),
        migrations.AddField(
            model_name='demandesang',
            name='ville',
            field=models.CharField(default='OUAGA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandesang',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='hopitaux.hopital'),
        ),
        migrations.AlterField(
            model_name='demandesang',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SATISFAITE', 'Satisfaite'), ('REFUSEE', 'Refusée'), ('EXPIREE', 'Expirée')], default='ACTIVE', max_length=15),
        ),
        migrations.AlterField(
            model_name='demandesang',
            name='volume_ml',
            field=models.PositiveIntegerField(help_text='Volume requis en millilitres'),
        ),
    ]
