# Generated by Django 6.0.1 on 2026-01-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_demandesang_contact_demandesang_hopital_autre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandesang',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='demandesang',
            name='hopital_autre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='demandesang',
            name='volume_ml',
            field=models.PositiveIntegerField(default=450, help_text='450 ml par défaut pour un patient'),
        ),
    ]
