# Generated by Django 6.0.1 on 2026-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('DEMANDEUR', 'Demandeur'), ('DONNEUR', 'Donneur'), ('HOPITAL', 'Hôpital'), ('ADMIN', 'Administrateur')], default='DEMANDEUR', max_length=20),
        ),
    ]
