# Generated by Django 6.0.1 on 2026-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='groupe_sanguin',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='est_patient',
            field=models.BooleanField(default=False, verbose_name='Est patient'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='est_donneur',
            field=models.BooleanField(default=False, verbose_name='Est donneur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
    ]
