# Generated by Django 6.0.1 on 2026-01-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_remove_utilisateur_groupe_sanguin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_donneur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_patient',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='recevoir_notifications',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('DONNEUR', 'Donneur'), ('HOPITAL', 'Hôpital'), ('ADMIN', 'Administrateur')], default='DONNEUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
