# Generated by Django 6.0.1 on 2026-01-30 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hopitaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('INCONNU', 'Inconnu'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=7)),
                ('volume_ml', models.PositiveIntegerField(default=0)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='hopitaux.hopital')),
            ],
            options={
                'verbose_name': 'Stock de sang',
                'verbose_name_plural': 'Stocks de sang',
                'unique_together': {('hopital', 'groupe_sanguin')},
            },
        ),
    ]
